version: '3'
services:
  frr:
    image: frrouting/frr
    container_name: gateway_frr
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
    volumes:
      - ./frr:/etc/frr
      # - ./frr/var/run/frr/:/var/run/frr/
      - ./frr/var/log/:/var/log/
    network_mode: none
